/**
 * 로컬 개발 전용: VITE_SAFEMAP_SERVICE_KEY 없을 때만 App에서 사용.
 * normalizeCharger 결과와 동일한 형태 + dataSource: 'dev-mock'.
 * 표시명은 실 API와 혼동되지 않게 하되, (샘플)/가짜 진행·잔여시간 등은 넣지 않는다.
 */
import { getChgerTyLabel, getSpeedCategory, getDisplayChgerLabel } from '../api/safemapEv.js'

/** 목업 행 식별(디버깅·분기용). UI에 표시하지 않음. */
export const EV_DATA_SOURCE_DEV_MOCK = 'dev-mock'

function mk(partial) {
  const chgerTy = partial.chgerTy || '4'
  return {
    ...partial,
    dataSource: EV_DATA_SOURCE_DEV_MOCK,
    chgerTy,
    chgerTyLabel: getChgerTyLabel(chgerTy),
    speedCategory: getSpeedCategory(chgerTy),
    displayChgerLabel: getDisplayChgerLabel(chgerTy),
  }
}

export function getDevMockEvChargers() {
  return [
    mk({
      id: 'dev-ev-1',
      statId: 'dev-place-seoul-station',
      statNm: '서울역 인근 급속',
      chgerId: '01',
      stat: '2',
      statUpdDt: '2025-03-01 09:00:00',
      chgerTy: '4',
      useTm: '24시간',
      busiNm: '한빛이차저',
      telno: '1588-0000',
      adres: '서울특별시 용산구 한강대로 405',
      rnAdres: '한강대로 405',
      outputKw: '50',
      lat: 37.5547,
      lng: 126.9707,
      ctprvnCd: '11',
      sggCd: '11170',
    }),
    mk({
      id: 'dev-ev-2',
      statId: 'dev-place-seoul-station',
      statNm: '서울역 인근 급속',
      chgerId: '02',
      stat: '3',
      statUpdDt: '2025-03-01 09:05:00',
      chgerTy: '4',
      useTm: '24시간',
      busiNm: '한빛이차저',
      telno: '1588-0000',
      adres: '서울특별시 용산구 한강대로 405',
      rnAdres: '한강대로 405',
      outputKw: '50',
      lat: 37.5547,
      lng: 126.9707,
      ctprvnCd: '11',
      sggCd: '11170',
    }),
    mk({
      id: 'dev-ev-3',
      statId: 'dev-place-gwanghwamun',
      statNm: '광화문 완속',
      chgerId: '01',
      stat: '2',
      statUpdDt: '2025-03-01 08:00:00',
      chgerTy: '2',
      useTm: '06:00~24:00',
      busiNm: '그린모빌리티',
      telno: '',
      adres: '서울특별시 종로구 세종대로 175',
      rnAdres: '세종대로 175',
      outputKw: '7',
      lat: 37.572,
      lng: 126.9769,
      ctprvnCd: '11',
      sggCd: '11110',
    }),
    mk({
      id: 'dev-ev-4',
      statId: 'dev-place-yeouido',
      statNm: '여의도 공원',
      chgerId: 'A',
      stat: '5',
      statUpdDt: '2025-02-28 18:00:00',
      chgerTy: '6',
      useTm: '24시간',
      busiNm: '한빛이차저',
      telno: '02-0000-1234',
      adres: '서울특별시 영등포구 여의동로 330',
      rnAdres: '여의동로 330',
      outputKw: '100',
      lat: 37.5311,
      lng: 126.9242,
      ctprvnCd: '11',
      sggCd: '11560',
    }),
    mk({
      id: 'dev-ev-5',
      statId: 'dev-place-yeouido',
      statNm: '여의도 공원',
      chgerId: 'B',
      stat: '2',
      statUpdDt: '2025-03-01 10:00:00',
      chgerTy: '6',
      useTm: '24시간',
      busiNm: '한빛이차저',
      telno: '02-0000-1234',
      adres: '서울특별시 영등포구 여의동로 330',
      rnAdres: '여의동로 330',
      outputKw: '100',
      lat: 37.5311,
      lng: 126.9242,
      ctprvnCd: '11',
      sggCd: '11560',
    }),
    mk({
      id: 'dev-ev-6',
      statId: 'dev-place-gangnam',
      statNm: '강남역 콤보',
      chgerId: '1',
      stat: '2',
      statUpdDt: '2025-03-01 11:00:00',
      chgerTy: '10',
      useTm: '24시간',
      busiNm: '메트로EV',
      telno: '',
      adres: '서울특별시 강남구 강남대로 396',
      rnAdres: '강남대로 396',
      outputKw: '350',
      lat: 37.498,
      lng: 127.0276,
      ctprvnCd: '11',
      sggCd: '11680',
    }),
  ]
}
